/**
 * get list: getlist, getlist success, getlist fail
 */
export const GETCOMBO = "DISHMANAGAMENT/GETCOMBO";
export const GETCOMBO_SUCCESS = "DISHMANAGAMENT/GETCOMBO_SUCCESS";
export const GETCOMBO_FAIL = "DISHMANAGAMENT/GETCOMBO_FAIL";
/**
 * const get combo id
 */
export const GETCOMBOBYID = "DISHMANAGAMENT/GETCOMBOBYID";
export const GETCOMBOBYID_SUCCESS = "DISHMANAGAMENT/GETCOMBOBYID_SUCCESS";
export const GETCOMBOBYID_FAIL = "DISHMANAGAMENT/GETCOMBOBYID_FAIL";
/**
 * create: create combo, create combo success, create combo fail
 */
export const CREATECOMBO = "DISHMANAGAMENT/CREATECOMBO";
export const CREATECOMBO_SUCCESS = "DISHMANAGAMENT/CREATECOMBO_SUCCESS";
export const CREATECOMBO_FAIL = "DISHMANAGAMENT/CREATECOMBO_FAIL"
/**
 * update: update combo, update combo success, update combo fail
 */
export const UPDATECOMBO = "DISHMANAGAMENT/UPDATECOMBO";
export const UPDATECOMBO_SUCCESS = "DISHMANAGAMENT/UPDATECOMBO_SUCCESS";
export const UPDATECOMBO_FAIL = "DISHMANAGAMENT/UPDATECOMBO_FAIL"
/**
 * delete: delete combo, delete combo success, delete combo fail
 */
export const DELETECOMBO = "DISHMANAGAMENT/DELETECOMBO";
export const DELETECOMBO_SUCCESS = "DISHMANAGAMENT/DELETECOMBO_SUCCESS";
export const DELETECOMBO_FAIL = "DISHMANAGAMENT/DELETECOMBO_FAIL";

export const RESETCOMBODETAIL = "DISHMANAGAMENT/RESETCOMBODETAIL";
export const RESETCOMBODETAIL_SUCCESS = "DISHMANAGAMENT/RESETCOMBODETAIL_SUCCESS";
export const RESETCOMBODETAIL_FAIL = "DISHMANAGAMENT/RESETCOMBODETAIL_FAIL";

/**
 * get Item
 */
export const GETITEMLIST = "GETITEMLIST";
export const GETITEMLIST_SUCCESS = "GETITEMLIST_SUCCESS";
export const GETITEMLIST_FAIL = "GETITEMLIST_FAIL";

export const GETITEM_COMBOLIST = "GETITEM_COMBOLIST";
export const GETITEM_COMBOLIST_SUCCESS = "GETITEM_COMBOLIST_SUCCESS";
export const GETITEM_COMBOLIST_FAIL = "GETITEM_COMBOLIST_FAIL";

export const RESETITEMCOMBOLIST = "DISHMANAGAMENT/RESETITEMCOMBOLIST";

export const LOADDISHICON = "LOADDISHICON";
export const GET_DISHICON_SUCCESS = "GET_DISHICON_SUCCESS";