export { default as AreaList } from './AreaManagement/pages/AreaList';
export { default as AreaNew } from './AreaManagement/pages/AreaNew';
export { default as AreaEdit } from './AreaManagement/pages/AreaEdit';
export { default as TableList } from './TableList/pages/TableList';
export { default as PaymentList } from './PaymentManagement/pages/PaymentList';
export { default as PaymentOrder } from './PaymentManagement/pages/PaymentOrder';
export { default as TableArrangement } from './TableArrangement/TableArrangement';

export { default as CheckInPage } from './CheckInOutManagement/components/CheckInPage';
export { default as CheckOutPage } from './CheckInOutManagement/components/CheckOutPage';
export { default as PersonalCalendarPage } from './CheckInOutManagement/components/PersonalCalendarPage'
export { default as RegisterOTPage } from './CheckInOutManagement/components/AddOT/RegisterOTPage'
export { default as RegisterWorkInsteadPage } from "./CheckInOutManagement/components/WorkInstead/RegisterWorkInsteadPage";
export { default as CalendarStaffPage } from "./CheckInOutManagement/components/CalendarStaff/CalendarStaffPage";
export { default as TakeLeavePage } from "./CheckInOutManagement/components/TakeLeave/TakeLeavePage";

export { default as MainManagement } from "./MainManagement";
export { default as FoodManagement } from "./FoodManagement";
export { default as TableListManagement } from "./TableListManagement";
export { default as FoodListIsProcessing } from "./FoodListIsProcessing";
export { default as LoginScreen } from "./Login";
export { default as ListOfBookedTables } from "./ListOfBookedTables";
export { default as UserManagement } from "./UserManagement";
export { default as Setting } from "./SettingScreen";
export { default as PromotionManagement } from "./PromotionManagement";
export { default as FoodCategoryManagement } from "./FoodCategoryManagement";
export { default as DishManagement } from "./DishManagement";
export { default as TakeAwayScreen } from "./TakeAwayScreen";
export { default as BookingTable } from "./BookingTable";
export { default as PromotionManagements } from "./PromotionManagements";
export { default as ReportManagement } from "./ReportManagement";
export { default as CalendarManagement } from "./CalendarManagement";
export { default as DetailRestaurant } from "./DetailRestaurant";
export { default as ShiftManagement } from "./ShiftManagement";
export { default as PaymentRequest } from "./RequestPayment";
export { default as PaymentRequestDetail } from "./RequestPayment/components/RequestPaymentDetail";
export { default as OrderedList } from "./RequestPayment/components/OrderedList";
export { default as ViewProvisiVotes } from "./RequestPayment/components/ViewProvisiVotes";
export { default as ProvisionalVotes } from "./RequestPayment/components/ProvisionalVotes";
export { default as PageNotFound } from "./PageNotFound";
export { default as ComboList } from "./TableList/pages/components/TableFeature/ComboList";
export { default as FoodList } from "./TableList/pages/components/TableFeature/FoodList";
export { default as PrintOrder } from "./PaymentManagement/pages/components/PrintOrder";
export { default as FoodListIsProcessingBar } from "./FoodListIsProcessingBar";
export { default as AddonManagement } from "./AddonManagement";
