export const BAREMPLOYEE = "role_3";
export const EMPLOYEE = "staff";
export const WAITING_ORDER = 1;
export const OUTOFF_ORDER = 5;
export const COMPLETED_ORDER = 4;

export const LIMIT_DISH = 10;
export const LIMIT_ORDER = 4;

export const TAB_DISH = 11;
export const TAB_ORDER = 22;

export const HEIGHT_FOOD_DEFAULT = 97;

export const NOTI_ACTION_CHANGE_ITEM = "change_item";
export const NOTI_ACTION_CANCEL_ITEM = "cancel_item";
export const NOTI_ACTION_STAFF_ORDER_ITEM = "staff_order_item";
export const NOTI_ACTION_DELIVERY_ITEM = "delivery_item";
// Các action của noti để update kitchen/bar
export const ACTION_UPDATE_KITCHENBAR = [
  "change_item",
  "cancel_item",
  "staff_order_item",
  "cancel_order",
  "delivery_item",
  "finished_payment",
]

// Các action của noti phải call api để update danh sách order của tab order/bàn
export const UPDATE_ORDER_LIST = [
  "staff_order_item",
  "cancel_order",
  "finished_payment",
]

// Các action của noti phải call api để update danh sách món ăn của order tab order/bàn
export const UPDATE_DISH_LIST_ORDER = [
  "cancel_order",
  "finished_payment",
]

export const GETAREALIST = "FOODLISTISPROCESSING/GETAREALIST";
export const GETAREALIST_SUCCESS = "FOODLISTISPROCESSING/GETAREALIST_SUCCESS";
export const GETAREALIST_FAIL = "FOODLISTISPROCESSING/GETAREALIST_FAIL";

export const GETORDERFOODLIST = "FOODLISTISPROCESSING/GETORDERFOODLIST";
export const GETORDERFOODLIST_SUCCESS = "FOODLISTISPROCESSING/GETORDERFOODLIST_SUCCESS";
export const GETORDERFOODLIST_FAIL = "FOODLISTISPROCESSING/GETORDERFOODLIST_FAIL";

export const GETORDERBYTABLE = "FOODLISTISPROCESSING/GETORDERBYTABLE";
export const GETORDERBYTABLE_SUCCESS = "FOODLISTISPROCESSING/GETORDERBYTABLE_SUCCESS";
export const GETORDERBYTABLE_FAIL = "FOODLISTISPROCESSING/GETORDERBYTABLE_FAIL";

export const GETDISHBYORDER = "FOODLISTISPROCESSING/GETDISHBYORDER";
export const GETDISHBYORDER_SUCCESS = "FOODLISTISPROCESSING/GETDISHBYORDER_SUCCESS";
export const GETDISHBYORDER_FAIL = "FOODLISTISPROCESSING/GETDISHBYORDER_FAIL";

export const UPDATEDORDERITEMISCOMPLETED = "FOODLISTISPROCESSING/UPDATEDORDERITEMISCOMPLETED";
export const UPDATEDORDERITEMISCOMPLETED_SUCCESS = "FOODLISTISPROCESSING/UPDATEDORDERITEMISCOMPLETED_SUCCESS";
export const UPDATEDORDERITEMISCOMPLETED_FAIL = "FOODLISTISPROCESSING/UPDATEDORDERITEMISCOMPLETED_FAIL";

export const UPDATEORDERITEMISOFF = "FOODLISTISPROCESSING/UPDATEORDERITEMISOFF";
export const UPDATEORDERITEMISOFF_SUCCESS = "FOODLISTISPROCESSING/UPDATEORDERITEMISOFF_SUCCESS";
export const UPDATEORDERITEMISOFF_FAIL = "FOODLISTISPROCESSING/UPDATEORDERITEMISOFF_FAIL";

export const ADDNOFITICATION = "FOODLISTISPROCESSING/ADDNOFITICATION";
export const ADDNOFITICATION_SUCCESS = "FOODLISTISPROCESSING/ADDNOFITICATION_SUCCESS";
export const ADDNOFITICATION_FAIL = "FOODLISTISPROCESSING/ADDNOFITICATION_FAIL";

export const SETDISHPAGE = "FOODLISTISPROCESSING/SETDISHPAGE";
export const SETORDERPAGE = "FOODLISTISPROCESSING/SETORDERPAGE";

export const SEARCHORDER = "FOODLISTISPROCESSING/SEARCHORDER";
export const SEARCHORDER_SUCCESS = "FOODLISTISPROCESSING/SEARCHORDER_SUCCESS";
export const SEARCHORDER_FAIL = "FOODLISTISPROCESSING/SEARCHORDER_FAIL";

export const STARTLOADING = "FOODLISTISPROCESSING/STARTLOADING";
export const STOPLOADING = "FOODLISTISPROCESSING/STOPLOADING";

export const GETUSERINFO = "FOODLISTISPROCESSING/GETUSERINFO";

export const UPDATEKITCHENBAR = "FOODLISTISPROCESSING/UPDATEKITCHENBAR"
export const SHOWMESSAGEBYNOTI = "FOODLISTISPROCESSING/SHOWMESSAGEBYNOTI"
export const UPDATEORDERBYNOTI = "FOODLISTISPROCESSING/UPDATEORDERBYNOTI";
export const GETPARAMSTABFOOD = "FOODLISTISPROCESSING/GETPARAMSTABFOOD";

export const GETACCOUNTINFOSTAFF = "FOODLISTISPROCESSING/GETACCOUNTINFOSTAFF";
export const GETACCOUNTINFOSTAFF_SUCCESS = "FOODLISTISPROCESSING/GETACCOUNTINFOSTAFF_SUCCESS";
export const GETACCOUNTINFOSTAFF_FAIL = "FOODLISTISPROCESSING/GETACCOUNTINFOSTAFF_FAIL";