export const GETPROMOTIONS = "PROMOTION/GETPROMOTIONS";
export const GETPROMOTIONS_SUCCESS = "PROMOTION/GETPROMOTIONS_SUCCESS";
export const GETPROMOTIONS_FAIL = "PROMOTION/GETPROMOTIONS_FAIL";

export const CREATEPROMOTION = "PROMOTION/CREATEPROMOTION";
export const CREATEPROMOTION_SUCCESS = "PROMOTION/CREATEPROMOTION_SUCCESS";
export const CREATEPROMOTION_FAIL = "PROMOTION/CREATEPROMOTION_FAIL";

export const DELETEPROMOTION = "PROMOTION/DELETEPROMOTION";
export const DELETEPRMOTION_SUCCESS = "PROMOTION/DELETEPRMOTION_SUCCESS";
export const DELETEPRMOTION_FAIL = "PROMOT/DELETEPRMOTION_FAIL";

export const EDITPROMOTION = "PROMOTION/EDITPROMOTION";
export const EDITPROMOTION_SUCCESS = "PROMOT/EDITPROMOTION_SUCCESS";
export const EDITPROMOTION_FAIL = "PROMOTION/EDITPROMOTION_FAIL";
