export const DAY = 1;
export const WEEK = 7;
export const MONTH = 4;
export const DAYS_EN = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export const DAYS_JP = ['日曜日', '月曜', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'];
export const DAYS_VN = ['Chủ Nhật', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'];
export const TIME_GRID = ['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00']
export const LESS_THAN = "LESS_THAN";
export const GREATER_THAN = "GREATER_THAN";
export const WIDTH_MAX = 550;
export const WIDTH_WORK_SHIFT = 350;
export const DISTANCE_BETWEEN_TWO_WORK_SHIFTS = 60;
export const DISTANCE_FIRST_ROW_WITH_TOP_PARENT = 25;
export const DISTANCE_LEFT_PARENT_WITH_FIRST_WORK_SHIFT = 170;
export const DISTANCE_BETWEEN_TWO_ROW = 50;
export const DISTANCE_BETWEEN_LAST_WORK_SHIFT_WITH_RIGHT_PARENT = 50;
export const CHECK_IN = "check in";
export const CHECK_OUT = "check out";
export const OVER_TIME_CANCEL_WORK_SHIFT = "OVERTIME";
export const NO_OVER_TIME_CANCEL_WORK_SHIFT = "NO_OVERTIME";
export const ZERO = 0;
export const MONTH_GRID = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 35, 37, 38, 39, 40, 41
]
export const WORK = 1;
export const WORK_PART_TIME = 2;
export const OFF = 3;

export const GETCALENDAR = "CALENDARMANAGEMENT/GETCALENDAR";
export const GETCALENDAR_SUCCESS = "CALENDARMANAGEMENT/GETCALENDAR_SUCCESS";
export const GETCALENDAR_FAIL = "CALENDARMANAGEMENT/GETCALENDAR_FAIL";

export const UPDATETAKELEAVE = "CALENDARMANAGEMENT/UPDATETAKELEAVE";
export const UPDATETAKELEAVE_SUCCESS = "CALENDARMANAGEMENT/UPDATETAKELEAVE_SUCCESS";
export const UPDATETAKELEAVE_FAIL = "CALENDARMANAGEMENT/UPDATETAKELEAVE_FAIL";

export const UPDATECANCELTAKELEAVE = "CALENDARMANAGEMENT/UPDATECANCELTAKELEAVE";
export const UPDATECANCELTAKELEAVE_SUCCESS = "CALENDARMANAGEMENT/UPDATECANCELTAKELEAVE_SUCCESS";
export const UPDATECANCELTAKELEAVE_FAIL = "CALENDARMANAGEMENT/UPDATECANCELTAKELEAVE_FAIL";

export const GETACCOUNTLIST = "CALENDARMANAGEMENT/GETACCOUNTLIST";
export const GETACCOUNTLIST_SUCCESS = "CALENDARMANAGEMENT/GETACCOUNTLIST_SUCCESS";
export const GETACCOUNTLIST_FAIL = "CALENDARMANAGEMENT/GETACCOUNTLIST_FAIL";

export const ADDEMPLOYEESTOSHIFT = "CALENDARMANAGEMENT/ADDEMPLOYEESTOSHIFT";
export const ADDEMPLOYEESTOSHIFT_SUCCESS = "CALENDARMANAGEMENT/ADDEMPLOYEESTOSHIFT_SUCCESS";
export const ADDEMPLOYEESTOSHIFT_FAIL = "CALENDARMANAGEMENT/ADDEMPLOYEESTOSHIFT_FAIL";

export const DELETEEMPLOYEETOSHIFT = "CALENDARMANAGEMENT/DELETEEMPLOYEETOSHIFT";
export const DELETEEMPLOYEETOSHIFT_SUCCESS = "CALENDARMANAGEMENT/DELETEEMPLOYEETOSHIFT_SUCCESS";
export const DELETEEMPLOYEETOSHIFT_FAIL = "CALENDARMANAGEMENT/DELETEEMPLOYEETOSHIFT_FAIL";

export const GETCALENDARWEEK = "CALENDARMANAGEMENT/GETCALENDARWEEK";
export const GETCALENDARWEEK_SUCCESS = "CALENDARMANAGEMENT/GETCALENDARWEEK_SUCCESS";
export const GETCALENDARWEEK_FAIL = "CALENDARMANAGEMENT/GETCALENDARWEEK_FAIL";

export const UPDATEUI = "CALENDARMANAGEMENT/UPDATEUI";
export const NOUPDATEUI = "CALENDARMANAGEMENT/NOUPDATEUI";

export const GETWORKEDEMPLOYEELIST = "CALENDARMANAGEMENT/GETWORKEDEMPLOYEELIST";
export const GETWORKEDEMPLOYEELIST_SUCCESS = "CALENDARMANAGEMENT/GETWORKEDEMPLOYEELIST_SUCCESS";
export const GETWORKEDEMPLOYEELIST_FAIL = "CALENDARMANAGEMENT/GETWORKEDEMPLOYEELIST_FAIL";

export const GETOFFEMPLOYEELIST = "CALENDARMANAGEMENT/GETOFFEMPLOYEELIST";
export const GETOFFEMPLOYEELIST_SUCCESS = "CALENDARMANAGEMENT/GETOFFEMPLOYEELIST_SUCCESS";
export const GETOFFEMPLOYEELIST_FAIL = "CALENDARMANAGEMENT/GETOFFEMPLOYEELIST_FAIL";

export const GETCALENDAROFUSER = "CALENDARMANAGEMENT/GETCALENDAROFUSER";
export const GETCALENDAROFUSER_SUCCESS = "CALENDARMANAGEMENT/GETCALENDAROFUSER_SUCCESS";
export const GETCALENDAROFUSER_FAIL = "CALENDARMANAGEMENT/GETCALENDAROFUSER_FAIL";

export const GETLISTSHIFT = "CALENDARMANAGEMENT/GETLISTSHIFT";
export const GETLISTSHIFT_SUCCESS = "CALENDARMANAGEMENT/GETLISTSHIFT_SUCCESS";
export const GETLISTSHIFT_FAIL = "CALENDARMANAGEMENT/GETLISTSHIFT_FAIL";

export const ADDOTSHIFT = "CALENDARMANAGEMENT/ADDOTSHIFT";
export const ADDOTSHIFT_SUCCESS = "CALENDARMANAGEMENT/ADDOTSHIFT_SUCCESS";
export const ADDOTSHIFT_FAIL = "CALENDARMANAGEMENT/ADDOTSHIFT_FAIL";

export const GETCHECKINOUT = "CALENDARMANAGEMENT/GETCHECKINOUT";
export const GETCHECKINOUT_SUCCESS = "CALENDARMANAGEMENT/GETCHECKINOUT_SUCCESS";
export const GETCHECKINOUT_FAIL = "CALENDARMANAGEMENT/GETCHECKINOUT_FAIL";

export const RESETCHECKINOUT = "CALENDARMANAGEMENT/RESETCHECKINOUT";

export const GETTOTALSHIFT = "CALENDARMANAGEMENT/GETTOTALSHIFT";
export const GETTOTALSHIFT_SUCCESS = "CALENDARMANAGEMENT/GETTOTALSHIFT_SUCCESS";
export const GETTOTALSHIFT_FAIL = "CALENDARMANAGEMENT/GETTOTALSHIFT_FAIL";

