export const GETINFOTAXSETTING = "SETTING/GETINFOTAXSETTING";
export const GETINFOTAXSETTING_SUCCESS = "SETTING/GETINFOTAXSETTING_SUCCESS";
export const GETINFOTAXSETTING_FAIL = "SETTING/GETINFOTAXSETTING_FAIL";

export const UPDATEINFOTAXSETTING = "SETTING/UPDATEINFOTAXSETTING";
export const UPDATEINFOTAXSETTING_SUCCESS = "SETTING/UPDATEINFOTAXSETTING_SUCCESS";
export const UPDATEINFOTAXSETTING_FAIL = "SETTING/UPDATEINFOTAXSETTING_FAIL";

export const GETPARTNERBYID = "SETTING/GETPARTNERBYID";
export const GETPARTNERBYID_SUCCESS = "SETTING/GETPARTNERBYID_SUCCESS";
export const GETPARTNERBYID_FAIL = "SETTING/GETPARTNERBYID_FAIL";

export const GETPRINTERBILLLIST = "SETTING/GETPRINTERBILLLIST";
export const GETPRINTERBILLLIST_SUCCESS = "SETTING/GETPRINTERBILLLIST_SUCCESS";
export const GETPRINTERBILLLIST_FAIL = "SETTING/GETPRINTERBILLLIST_FAIL";

export const GETPRINTERBILLBYID = "SETTING/GETPRINTERBILLBYID";
export const GETPRINTERBILLBYID_SUCCESS = "SETTING/GETPRINTERBILLBYID_SUCCESS";
export const GETPRINTERBILLBYID_FAIL = "SETTING/GETPRINTERBILLBYID_FAIL";

export const CREATEPRINTERBILL = "SETTING/CREATEPRINTERBILL";
export const CREATEPRINTERBILL_SUCCESS = "SETTING/CREATEPRINTERBILL_SUCCESS";
export const CREATEPRINTERBILL_FAIL = "SETTING/CREATEPRINTERBILL_FAIL";

export const DELETEPRINTERBILL = "SETTING/DELETEPRINTERBILL";
export const DELETEPRINTERBILL_SUCCESS = "SETTING/DELETEPRINTERBILL_SUCCESS";
export const DELETEPRINTERBILL_FAIL = "SETTING/DELETEPRINTERBILL_FAIL";

export const EDITPRINTERBILL = "SETTING/EDITPRINTERBILL";
export const EDITPRINTERBILL_SUCCESS = "SETTING/EDITPRINTERBILL_SUCCESS";
export const EDITPRINTERBILL_FAIL = "SETTING/EDITPRINTERBILL_FAIL"

export const GETPRINTERCHICKENBARLIST = "SETTING/GETPRINTERCHICKENBARLIST";
export const GETPRINTERCHICKENBARLIST_SUCCESS = "SETTING/GETPRINTERCHICKENBARLIST_SUCCESS";
export const GETPRINTERCHICKENBARLIST_FAIL = "SETTING/GETPRINTERCHICKENBARLIST_FAIL";

export const GETPRINTERCHICKENBARBYID = "SETTING/GETPRINTERCHICKENBARBYID";
export const GETPRINTERCHICKENBARBYID_SUCCESS = "SETTING/GETPRINTERCHICKENBARBYID_SUCCESS";
export const GETPRINTERCHICKENBARBYID_FAIL = "SETTING/GETPRINTERCHICKENBARBYID_FAIL";

export const CREATEPRINTERCHICKENBAR = "SETTING/CREATEPRINTERCHICKENBAR";
export const CREATEPRINTERCHICKENBAR_SUCCESS = "SETTING/CREATEPRINTERCHICKENBAR_SUCCESS";
export const CREATEPRINTERCHICKENBAR_FAIL = "SETTING/CREATEPRINTERCHICKENBAR_FAIL";

export const DELETEPRINTERCHICKENBAR = "SETTING/DELETEPRINTERCHICKENBAR";
export const DELETEPRINTERCHICKENBAR_SUCCESS = "SETTING/DELETEPRINTERCHICKENBAR_SUCCESS";
export const DELETEPRINTERCHICKENBAR_FAIL = "SETTING/DELETEPRINTERCHICKENBAR_FAIL";

export const EDITPRINTERCHICKENBAR = "SETTING/EDITPRINTERCHICKENBAR";
export const EDITPRINTERCHICKENBAR_SUCCESS = "SETTING/EDITPRINTERCHICKENBAR_SUCCESS";
export const EDITPRINTERCHICKENBAR_FAIL = "SETTING/EDITPRINTERCHICKENBAR_FAIL"