export const GETLISTPROMOTION = "PROMOTIONS/GETLISTPROMOTION"
export const GETLISTPROMOTION_SUCCESS = "PROMOTIONS/GETLISTPROMOTION_SUCCESS"
export const GETLISTPROMOTION_FAIL = "PROMOTIONS/GETLISTPROMOTION_FAIL";

export const GETLISTPROMOTIONBYSEARCH = "PROMOTIONS/GETLISTPROMOTIONBYSEARCH"
export const GETLISTPROMOTIONBYSEARCH_SUCCESS = "PROMOTIONS/GETLISTPROMOTIONBYSEARCH_SUCCESS"
export const GETLISTPROMOTIONBYSEARCH_FAIL = "PROMOTIONS/GETLISTPROMOTIONBYSEARCH_FAIL";

export const DELETEPROMOTION = "PROMOTIONS/DELETEPROMOTION";

export const GETLISTPROMOTIONDISCOUNT = "PROMOTIONS/GETLISTPROMOTIONDISCOUNT"
export const GETLISTPROMOTIONDISCOUNT_SUCCESS = "PROMOTIONS/GETLISTPROMOTIONDISCOUNT_SUCCESS"
export const GETLISTPROMOTIONDISCOUNT_FAIL = "PROMOTIONS/GETLISTPROMOTIONDISCOUNT_FAIL"

export const ADDPROMOTIONBILLDISCOUNT = "PROMOTIONS/ADDPROMOTIONBILLDISCOUNT"
export const ADDPROMOTIONBILLDISCOUNT_SUCCESS = "PROMOTIONS/ADDPROMOTIONBILLDISCOUNT_SUCCESS"
export const ADDPROMOTIONBILLDISCOUNT_FAIL = "PROMOTIONS/ADDPROMOTIONBILLDISCOUNT_FAIL";

export const GETPROMOTIONBILLDISCOUNTBYID = "PROMOTIONS/GETPROMOTIONBILLDISCOUNTBYID";
export const GETPROMOTIONBILLDISCOUNTBYID_SUCCESS = "PROMOTIONS/GETPROMOTIONBILLDISCOUNTBYID_SUCCESS";
export const GETPROMOTIONBILLDISCOUNTBYID_FAIL = "PROMOTIONS/GETPROMOTIONBILLDISCOUNTBYID_FAIL";

export const GETPROMOTIONITEMDISCOUNTBYID = "PROMOTIONS/GETPROMOTIONITEMDISCOUNTBYID";
export const GETPROMOTIONITEMDISCOUNTBYID_SUCCESS = "PROMOTIONS/GETPROMOTIONITEMDISCOUNTBYID_SUCCESS";
export const GETPROMOTIONITEMDISCOUNTBYID_FAIL = "PROMOTIONS/GETPROMOTIONITEMDISCOUNTBYID_FAIL";

export const GETPROMOTIONCOMBOITEMDISCOUNTBYID = "PROMOTIONS/GETPROMOTIONCOMBOITEMDISCOUNTBYID";
export const GETPROMOTIONCOMBOITEMDISCOUNTBYID_SUCCESS = "PROMOTIONS/GETPROMOTIONCOMBOITEMDISCOUNTBYID_SUCCESS";
export const GETPROMOTIONCOMBOITEMDISCOUNTBYID_FAIL = "PROMOTIONS/GETPROMOTIONCOMBOITEMDISCOUNTBYID_FAIL";

export const GETPROMOTIONVOUCHERDISCOUNTBYID = "PROMOTIONS/GETPROMOTIONVOUCHERDISCOUNTBYID";
export const GETPROMOTIONVOUCHERDISCOUNTBYID_SUCCESS = "PROMOTIONS/GETPROMOTIONVOUCHERDISCOUNTBYID_SUCCESS";
export const GETPROMOTIONVOUCHERDISCOUNTBYID_FAIL = "PROMOTIONS/GETPROMOTIONVOUCHERDISCOUNTBYID_FAIL";

export const RESETPROMOTIONBILLDISCOUNTBYID = "PROMOTIONS/RESETPROMOTIONBILLDISCOUNTBYID"

export const ADDPROMOTIONITEMDISCOUNT = "PROMOTIONS/ADDPROMOTIONITEMDISCOUNT"
export const ADDPROMOTIONITEMDISCOUNT_SUCCESS = "PROMOTIONS/ADDPROMOTIONITEMDISCOUNT_SUCCESS"
export const ADDPROMOTIONITEMDISCOUNT_FAIL = "PROMOTIONS/ADDPROMOTIONITEMDISCOUNT_FAIL"

export const ADDPROMOTIONCOMBOITEMDISCOUNT = "PROMOTIONS/ADDPROMOTIONCOMBOITEMDISCOUNT"
export const ADDPROMOTIONCOMBOITEMDISCOUNT_SUCCESS = "PROMOTIONS/ADDPROMOTIONCOMBOITEMDISCOUNT_SUCCESS"
export const ADDPROMOTIONCOMBOITEMDISCOUNT_FAIL = "PROMOTIONS/ADDPROMOTIONCOMBOITEMDISCOUNT_FAIL"

export const ADDPROMOTIONVOUCHERDISCOUNT = "PROMOTIONS/ADDPROMOTIONVOUCHERDISCOUNT"
export const ADDPROMOTIONVOUCHERDISCOUNT_SUCCESS = "PROMOTIONS/ADDPROMOTIONVOUCHERDISCOUNT_SUCCESS"
export const ADDPROMOTIONVOUCHERDISCOUNT_FAIL = "PROMOTIONS/ADDPROMOTIONVOUCHERDISCOUNT_FAIL";

export const EDITPROMOTIONBILLDISCOUNT = "PROMOTIONS/EDITPROMOTIONBILLDISCOUNT";

export const EDITPROMOTIONITEMDISCOUNT = "PROMOTIONS/EDITPROMOTIONITEMDISCOUNT";

export const EDITPROMOTIONCOMBOITEMDISCOUNT = "PROMOTIONS/EDITPROMOTIONCOMBOITEMDISCOUNT";

export const EDITPROMOTIONVOUCHERDISCOUNT = "PROMOTIONS/EDITPROMOTIONVOUCHERDISCOUNT";

export const GETLISTITEM = "PROMOTIONS/GETLISTITEM"
export const GETLISTITEM_SUCCESS = "PROMOTIONS/GETLISTITEM_SUCCESS"
export const GETLISTITEM_FAIL = "PROMOTIONS/GETLISTITEM_FAIL"

export const GETLISTCOMBOITEM = "PROMOTIONS/GETLISTCOMBOITEM"
export const GETLISTCOMBOITEM_SUCCESS = "PROMOTIONS/GETLISTCOMBOITEM_SUCCESS"
export const GETLISTCOMBOITEM_FAIL = "PROMOTIONS/GETLISTCOMBOITEM_FAIL"

export const SETPAGE = "PROMOTIONS/SETPAGE"