export const GETGROUPUSER = "USERMANAGAMENT/GETGROUPUSER";
export const GETGROUPUSER_SUCCESS = "USERMANAGAMENT/GETGROUPUSER_SUCCESS";
export const GETGROUPUSER_FAIL = "USERMANAGAMENT/GETGROUPUSER_FAIL";

export const GETACCOUNTINFO = "USERMANAGAMENT/GETACCOUNTINFO";
export const GETACCOUNTINFO_SUCCESS = "USERMANAGAMENT/GETACCOUNTINFO_SUCCESS";
export const GETACCOUNTINFO_FAIL = "USERMANAGAMENT/GETACCOUNTINFO_FAIL";

export const GETACCOUNTINFOSTAFF = "USERMANAGAMENT/GETACCOUNTINFOSTAFF";
export const GETACCOUNTINFOSTAFF_SUCCESS = "USERMANAGAMENT/GETACCOUNTINFOSTAFF_SUCCESS";
export const GETACCOUNTINFOSTAFF_FAIL = "USERMANAGAMENT/GETACCOUNTINFOSTAFF_FAIL";

export const CHANGEPASSWORD = "USERMANAGAMENT/CHANGEPASSWORD";
export const CHANGEPASSWORD_SUCCESS = "USERMANAGAMENT/CHANGEPASSWORD_SUCCESS";
export const CHANGEPASSWORD_FAIL = "USERMANAGAMENT/CHANGEPASSWORD_FAIL";

export const ADDGROUPUSER = "USERMANAGAMENT/ADDGROUPUSER";
export const ADDGROUPUSER_SUCCESS = "USERMANAGAMENT/ADDGROUPUSER_SUCCESS";
export const ADDGROUPUSER_FAIL = "USERMANAGAMENT/ADDGROUPUSER_FAIL";

export const DELETEGROUPUSER = "USERMANAGAMENT/DELETEGROUPUSER";
export const DELETEGROUPUSER_SUCCESS = "USERMANAGAMENT/DELETEGROUPUSER_SUCCESS";
export const DELETEGROUPUSER_FAIL = "USERMANAGAMENT/DELETEGROUPUSER_FAIL";

export const GETUSERLIST = "USERMANAGAMENT/GETUSERLIST";
export const GETUSERLIST_SUCCESS = "USERMANAGAMENT/GETUSERLIST_SUCCESS";
export const GETUSERLIST_FAIL = "USERMANAGAMENT/GETUSERLIST_FAIL";

export const GETPARTNERLIST = "USERMANAGAMENT/GETPARTNERLIST";
export const GETPARTNERLIST_SUCCESS = "USERMANAGAMENT/GETPARTNERLIST_SUCCESS";
export const GETPARTNERLIST_FAIL = "USERMANAGAMENT/GETPARTNERLIST_FAIL";

export const CREATEUSER = "USERMANAGAMENT/CREATEUSER";
export const CREATEUSER_SUCCESS = "USERMANAGAMENT/CREATEUSER_SUCCESS";
export const CREATEUSER_FAIL = "USERMANAGAMENT/CREATEUSER_FAIL";

export const GETROLELIST = "USERMANAGAMENT/GETROLELIST";
export const GETROLELIST_SUCCESS = "USERMANAGAMENT/GETROLELIST_SUCCESS";
export const GETROLELIST_FAIL = "USERMANAGAMENT/GETROLELIST_FAIL";

export const GETROLEBYID = "USERMANAGAMENT/GETROLEBYID";
export const GETROLEBYID_SUCCESS = "USERMANAGAMENT/GETROLEBYID_SUCCESS";
export const GETROLEBYID_FAIL = "USERMANAGAMENT/GETROLEBYID_FAIL";

export const EDITUSER = "USERMANAGAMENT/EDITUSER";
export const EDITUSER_SUCCESS = "USERMANAGAMENT/EDITUSER_SUCCESS";
export const EDITUSER_FAIL = "USERMANAGAMENT/EDITUSER_FAIL";

export const DELETEUSER = "USERMANAGAMENT/DELETEUSER";
export const DELETEUSER_SUCCESS = "USERMANAGAMENT/DELETEUSER_SUCCESS";
export const DELETEUSER_FAIL = "USERMANAGAMENT/DELETEUSER_FAIL";

export const EDITGROUPUSER = "USERMANAGAMENT/EDITGROUPUSER";
export const EDITGROUPUSER_SUCCESS = "USERMANAGAMENT/EDITGROUPUSER_SUCCESS";
export const EDITGROUPUSER_FAIL = "USERMANAGAMENT/EDITGROUPUSER_FAIL";

export const GET_LIST_AREA = "USERMANAGAMENT/GET_LIST_AREA";
export const GET_LIST_AREA_SUCCESS = "USERMANAGAMENT/GET_LIST_AREA_SUCCESS";
export const GET_LIST_AREA_FAILURE = "USERMANAGAMENT/GET_LIST_AREA_FAILURE";

export const ADD_OTSHIFT_TOSTAFF = "USERMANAGAMENT/ADD_OTSHIFT_TOSTAFF";
export const ADD_OTSHIFT_TOSTAFF_SUCCESS = "USERMANAGAMENT/ADD_OTSHIFT_TOSTAFF_SUCCESS";
export const ADD_OTSHIFT_TOSTAFF_FAIL = "USERMANAGAMENT/ADD_OTSHIFT_TOSTAFF_FAIL";

export const ADDSHIFTFFORSTAFF = "USERMANAGAMENT/ADDSHIFTFFORSTAFF";
export const ADDSHIFTFFORSTAFF_SUCCESS = "USERMANAGAMENT/ADDSHIFTFFORSTAFF_SUCCESS";
export const ADDSHIFTFFORSTAFF_FAIL = "USERMANAGAMENT/ADDSHIFTFFORSTAFF_FAIL";

export const DELETE_OTSHIFTBYID = "USERMANAGAMENT/DELETE_OTSHIFTBYID";

export const DELETE_TAKElEAVEBYID = "USERMANAGAMENT/DELETE_TAKElEAVEBYID";

export const GETLISTOTCHANGEDAY = "USERMANAGAMENT/GETLISTOTCHANGEDAY";
export const GETLISTOTCHANGEDAY_SUCCESS = "USERMANAGAMENT/GETLISTOTCHANGEDAY_SUCCESS";
export const GETLISTOTCHANGEDAY_FAIL = "USERMANAGAMENT/GETLISTOTCHANGEDAY_FAIL";

export const GETLISTTAKELEAVE = "USERMANAGAMENT/GETLISTTAKELEAVE";
export const GETLISTTAKELEAVE_SUCCESS = "USERMANAGAMENT/GETLISTTAKELEAVE_SUCCESS";
export const GETLISTTAKELEAVE_FAIL = "USERMANAGAMENT/GETLISTTAKELEAVE_FAIL";

export const GETLISTTAKELEAVEBYDAY = "USERMANAGAMENT/GETLISTTAKELEAVEBYDAY";
export const GETLISTTAKELEAVEBYDAY_SUCCESS = "USERMANAGAMENT/GETLISTTAKELEAVEBYDAY_SUCCESS";
export const GETLISTTAKELEAVEBYDAY_FAIL = "USERMANAGAMENT/GETLISTTAKELEAVEBYDAY_FAIL";

export const ADDDAYTAKELEAVE = "USERMANAGAMENT/ADDDAYTAKELEAVE";
export const ADDDAYTAKELEAVE_SUCCESS = "USERMANAGAMENT/ADDDAYTAKELEAVE_SUCCESS";
export const ADDDAYTAKELEAVE_FAIL = "USERMANAGAMENT/ADDDAYTAKELEAVE_FAIL";

export const GETLISTCHECKIN_OUT = "USERMANAGAMENT/GETLISTCHECKIN_OUT";
export const GETLISTCHECKIN_OUT_SUCCESS = "USERMANAGAMENT/GETLISTCHECKIN_OUT_SUCCESS";
export const GETLISTCHECKIN_OUT_FAIL = "USERMANAGAMENT/GETLISTCHECKIN_OUT_FAIL";

export const ADDCHECKIN_OUT = "USERMANAGAMENT/ADDCHECKIN_OUT";
export const ADDCHECKIN_OUT_SUCCESS = "USERMANAGAMENT/ADDCHECKIN_OUT_SUCCESS";
export const ADDCHECKIN_OUT_FAIL = "USERMANAGAMENT/ADDCHECKIN_OUT_FAIL";

export const EDITCHECKIN_OUT = "USERMANAGAMENT/EDITCHECKIN_OUT";
export const EDITCHECKIN_OUT_SUCCESS = "USERMANAGAMENT/EDITCHECKIN_OUT_SUCCESS";
export const EDITCHECKIN_OUT_FAIL = "USERMANAGAMENT/EDITCHECKIN_OUT_FAIL";

export const DELETECHECKIN_OUT = "USERMANAGAMENT/DELETECHECKIN_OUT";

export const GETLIST_HISTORYCHECK = "USERMANAGAMENT/GETLIST_HISTORYCHECK";
export const GETLIST_HISTORYCHECK_SUCCESS = "USERMANAGAMENT/GETLIST_HISTORYCHECK_SUCCESS";
export const GETLIST_HISTORYCHECK_FAIL = "USERMANAGAMENT/GETLIST_HISTORYCHECK_FAIL";

export const GETLISTWEEKDAYSHIFT = "USERMANAGAMENT/GETLISTWEEKDAYSHIFT";
export const GETLISTWEEKDAYSHIFT_SUCCESS = "USERMANAGAMENT/GETLISTWEEKDAYSHIFT_SUCCESS";
export const GETLISTWEEKDAYSHIFT_FAIL = "USERMANAGAMENT/GETLISTWEEKDAYSHIFT_FAIL";

export const AREA = [
  {
    id: 1,
    name: "Nguyễn Văn A"
  },
  {
    id: 2,
    name: "Nguyễn Văn B"
  },
  {
    id: 3,
    name: "Nguyễn Văn C"
  },
  {
    id: 4,
    name: "Nguyễn Văn D"
  },
  {
    id: 5,
    name: "Nguyễn Văn E"
  },
  {
    id: 6,
    name: "Nguyễn Văn F"
  },

]
/**
 * CREAT SHIFT
 */
export const LISTSHIFT = "USERMANAGAMENT/LISTSHIFT";
export const LISTSHIFT_SUCCESS = "USERMANAGAMENT/LISTSHIFT_SUCCESS";
export const LISTSHIFT_FAIL = "USERMANAGAMENT/LISTSHIFT_FAIL";

export const LISTDAY = "USERMANAGAMENT/LISTDAY";
export const LISTDAY_SUCCESS = "USERMANAGAMENT/LISTDAY_SUCCESS";
export const LISTDAY_FAIL = "USERMANAGAMENT/LISTDAY_FAIL";

export const GETLISTOVERSHIFT = "USERMANAGAMENT/GETLISTOVERSHIFT";
export const GETLISTOVERSHIFT_SUCCESS = "USERMANAGAMENT/GETLISTOVERSHIFT_SUCCESS";
export const GETLISTOVERSHIFT_FAIL = "USERMANAGAMENT/GETLISTOVERSHIFT_FAIL";

export const LISTSHIFTCALENDAROFUSER = "USERMANAGAMENT/LISTSHIFTCALENDAROFUSER";
export const LISTSHIFTCALENDAROFUSER_SUCCESS = "USERMANAGAMENT/LISTSHIFTCALENDAROFUSER_SUCCESS";
export const LISTSHIFTCALENDAROFUSER_FAIL = "USERMANAGAMENT/LISTSHIFTCALENDAROFUSER_FAIL";

export const UPDATEOVERSHIFT = "USERMANAGAMENT/UPDATEOVERSHIFT";

export const UPDATETAKELEAVESHIFT = "USERMANAGAMENT/UPDATETAKELEAVESHIFT";

export const LIMIT_USER_LIST = 10;

export const LIST_ROLE_FOR_CONSTRACT_RESTAURANT = [
  "role_8", //QUAN LY KHU VUC
  "role_7", //QUAN LY BAN
  "role_13", //QUAN LY MON ANs
  "role_14", //QUAN LY DANH MUC MON AN
  "role_9", //QUAN LY SUAT AN
  "role_15", //TAI KHOAN
  "role_10", //CAI DAT,
  "role_1"
]

//status for over time shift
export const ACCEPT = 1;
export const WAITING = 2;
export const CANCEL = 3;