export const GETITEMLIST = "TAKEAWAY/GETITEMLIST";
export const GETITEMLIST_SUCCESS = "TAKEAWAY/GETITEMLIST_SUCCESS";
export const GETITEMLIST_FAIL = "TAKEAWAY/GETITEMLIST_FAIL";

export const GETORDERFORM = "TAKEAWAY/GETORDERFORM";
export const GETORDERFORM_SUCCESS = "TAKEAWAY/GETORDERFORM_SUCCESS";
export const GETORDERFORM_FAIL = "TAKEAWAY/GETORDERFORM_FAIL";

export const CREATEORDER = "TAKEAWAY/CREATEORDER";
export const CREATEORDER_SUCCESS = "TAKEAWAY/CREATEORDER_SUCCESS";
export const CREATEORDER_FAIL = "TAKEAWAY/CREATEORDER_FAIL";

export const DELETEORDER = "TAKEAWAY/DELETEORDER";
export const DELETEORDER_SUCCESS = "TAKEAWAY/DELETEORDER_SUCCESS";
export const DELETEORDER_FAIL = "TAKEAWAY/DELETEORDER_FAIL";

export const DELIVERYCONFIRM = "TAKEAWAY/DELIVERYCONFIRM";
export const DELIVERYCONFIRM_SUCCESS = "TAKEAWAY/DELIVERYCONFIRM_SUCCESS";
export const DELIVERYCONFIRM_FAIL = "TAKEAWAY/DELIVERYCONFIRM_FAIL";

export const GETORDERITEMBYID = "TAKEAWAY/GETORDERITEMBYID";
export const GETORDERITEMBYID_SUCCESS = "TAKEAWAY/GETORDERITEMBYID_SUCCESS";
export const GETORDERITEMBYID_FAIL = "TAKEAWAY/GETORDERITEMBYID_FAIL";

export const GETCATEGORYITEMLIST = "TAKEAWAY/GETCATEGORYITEMLIST";
export const GETCATEGORYITEMLIST_SUCCESS = "TAKEAWAY/GETCATEGORYITEMLIST_SUCCESS";
export const GETCATEGORYITEMLIST_FAIL = "TAKEAWAY/GETCATEGORYITEMLIST_FAIL";

export const GETCOMBOITEMLIST = "TAKEAWAY/GETCOMBOITEMLIST";
export const GETCOMBOITEMLIST_SUCCESS = "TAKEAWAY/GETCOMBOITEMLIST_SUCCESS";
export const GETCOMBOITEMLIST_FAIL = "TAKEAWAY/GETCOMBOITEMLIST_FAIL";

export const GETPARTNERSETTING = "TAKEAWAY/GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS = "TAKEAWAY/GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "TAKEAWAY/GETPARTNERSETTING_FAIL";

export const GETCOMBOBYID = "TAKEAWAY/GETCOMBOBYID";
export const GETCOMBOBYID_SUCCESS = "TAKEAWAY/GETCOMBOBYID_SUCCESS";
export const GETCOMBOBYID_FAIL = "TAKEAWAY/GETCOMBOBYID_FAIL";

export const GETACCOUNTINFO = "TAKEAWAY/GETACCOUNTINFO";
export const GETACCOUNTINFO_SUCCESS = "TAKEAWAY/GETACCOUNTINFO_SUCCESS";
export const GETACCOUNTINFO_FAIL = "TAKEAWAY/GETACCOUNTINFO_FAIL";

export const PAYMENTORDER = "TAKEAWAY/PAYMENTORDER";
export const PAYMENTORDER_SUCCESS = "TAKEAWAY/PAYMENTORDER_SUCCESS";
export const PAYMENTORDER_FAIL = "TAKEAWAY/PAYMENTORDER_FAIL";

export const GETPARTNERBYID = "TAKEAWAY/GETPARTNERBYID";
export const GETPARTNERBYID_SUCCESS = "TAKEAWAY/GETPARTNERBYID_SUCCESS";
export const GETPARTNERBYID_FAIL = "TAKEAWAY/GETPARTNERBYID_FAIL";

export const GETORDERITEM = "TAKEAWAY/GETORDERITEM";
export const GETORDERITEM_SUCCESS = "TAKEAWAY/GETORDERITEM_SUCCESS";
export const GETORDERITEM_FAIL = "TAKEAWAY/GETORDERITEM_FAIL";

export const GETCHECKVOUCHER = "TAKEAWAY/GETCHECKVOUCHER";
export const GETCHECKVOUCHER_SUCCESS = "TAKEAWAY/GETCHECKVOUCHER_SUCCESS";
export const GETCHECKVOUCHER_FAIL = "TAKEAWAY/GETCHECKVOUCHER_FAIL";

export const GETBILLINFOBYID = "TAKEAWAY/GETBILLINFOBYID";
export const GETBILLINFOBYID_SUCCESS = "TAKEAWAY/GETBILLINFOBYID_SUCCESS";
export const GETBILLINFOBYID_FAIL = "TAKEAWAY/GETBILLINFOBYID_FAIL";

export const CANCELBILL = "TAKEAWAY/CANCELBILL";
export const CANCELBILL_SUCCESS = "TAKEAWAY/CANCELBILL_SUCCESS";
export const CANCELBILL_FAIL = "TAKEAWAY/CANCELBILL_FAIL";

export const ROLLBACKLORDER = "TAKEAWAY/ROLLBACKLORDER";



