export const PAGE = 1;
export const LIMIT = 20;

export const GETADDONLIST = "ADDONMANAGEMENT/GETADDONLIST";
export const GETADDONLIST_SUCCESS = "ADDONMANAGEMENT/GETADDONLIST_SUCCESS";
export const GETADDONLIST_FAIL = "ADDONMANAGEMENT/GETADDONLIST_FAIL";

export const CREATEADDON = "ADDONMANAGEMENT/CREATEADDON";
export const CREATEADDON_SUCCESS = "ADDONMANAGEMENT/CREATEADDON_SUCCESS";
export const CREATEADDON_FAIL = "ADDONMANAGEMENT/CREATEADDON_FAIL";

export const EDITADDON = "ADDONMANAGEMENT/EDITADDON";
export const EDITADDON_SUCCESS = "ADDONMANAGEMENT/EDITADDON_SUCCESS";
export const EDITADDON_FAIL = "ADDONMANAGEMENT/EDITADDON_FAIL";

export const DELETEADDON = "ADDONMANAGEMENT/DELETEADDON";
export const DELETEADDON_SUCCESS = "ADDONMANAGEMENT/DELETEADDON_SUCCESS";
export const DELETEADDON_FAIL = "ADDONMANAGEMENT/DELETEADDON_FAIL";

export const GETINFOVATSETTING = "ADDONMANAGEMENT/GETINFOVATSETTING";
export const GETINFOVATSETTING_SUCCESS = "ADDONMANAGEMENT/GETINFOVATSETTING_SUCCESS";
export const GETINFOVATSETTING_FAIL = "ADDONMANAGEMENT/GETINFOVATSETTING_FAIL";

export const START_LOADING = "ADDONMANAGEMENT/START_LOADING";
