export const GETCATEGORYITEMLIST = "FOODMANAGEMENT/GETCATEGORYITEMLIST";
export const GETCATEGORYITEMLIST_SUCCESS = "FOODMANAGEMENT/GETCATEGORYITEMLIST_SUCCESS";
export const GETCATEGORYITEMLIST_FAIL = "FOODMANAGEMENT/GETCATEGORYITEMLIST_FAIL";

export const CREATECATEGORYITEM = "FOODMANAGEMENT/CREATECATEGORYITEM";
export const CREATECATEGORYITEM_SUCCESS = "FOODMANAGEMENT/CREATECATEGORYITEM_SUCCESS";
export const CREATECATEGORYITEM_FAIL = "FOODMANAGEMENT/CREATECATEGORYITEM_FAIL";

export const DELETECATEGORYITEM = "FOODMANAGEMENT/DELETECATEGORYITEM";
export const DELETECATEGORYITEM_SUCCESS = "FOODMANAGEMENT/DELETECATEGORYITEM_SUCCESS";
export const DELETECATEGORYITEM_FAIL = "FOODMANAGEMENT/DELETECATEGORYITEM_FAIL";

export const EDITCATEGORYITEM = "FOODMANAGEMENT/EDITCATEGORYITEM";
export const EDITCATEGORYITEM_SUCCESS = "FOODMANAGEMENT/EDITCATEGORYITEM_SUCCESS";
export const EDITCATEGORYITEM_FAIL = "FOODMANAGEMENT/EDITCATEGORYITEM_FAIL"