export const BAREMPLOYEE = "role_3";
export const EMPLOYEE = "staff";
export const WAITING_ORDER = 1;
export const OUTOFF_ORDER = 5;
export const COMPLETED_ORDER = 4;

export const LIMIT_DISH = 10;
export const LIMIT_ORDER = 4;

export const TAB_DISH = 11;
export const TAB_ORDER = 22;

export const HEIGHT_FOOD_DEFAULT = 97;

export const NOTI_ACTION_CHANGE_ITEM = "change_item";
export const NOTI_ACTION_CANCEL_ITEM = "cancel_item";
export const NOTI_ACTION_STAFF_ORDER_ITEM = "staff_order_item";
export const NOTI_ACTION_DELIVERY_ITEM = "delivery_item";
// Các action của noti để update kitchen/bar
export const ACTION_UPDATE_KITCHENBAR = [
  "change_item",
  "cancel_item",
  "staff_order_item",
  "cancel_order",
  "delivery_item",
  "finished_payment",
]

// Các action của noti phải call api để update danh sách order của tab order/bàn
export const UPDATE_ORDER_LIST = [
  "staff_order_item",
  "cancel_order",
  "finished_payment",
]

// Các action của noti phải call api để update danh sách món ăn của order tab order/bàn
export const UPDATE_DISH_LIST_ORDER = [
  "cancel_order",
  "finished_payment",
]

export const GETAREALIST = "FOODLISTISPROCESSINGBAR/GETAREALIST";
export const GETAREALIST_SUCCESS = "FOODLISTISPROCESSINGBAR/GETAREALIST_SUCCESS";
export const GETAREALIST_FAIL = "FOODLISTISPROCESSINGBAR/GETAREALIST_FAIL";

export const GETORDERFOODLIST = "FOODLISTISPROCESSINGBAR/GETORDERFOODLIST";
export const GETORDERFOODLIST_SUCCESS = "FOODLISTISPROCESSINGBAR/GETORDERFOODLIST_SUCCESS";
export const GETORDERFOODLIST_FAIL = "FOODLISTISPROCESSINGBAR/GETORDERFOODLIST_FAIL";

export const GETORDERBYTABLE = "FOODLISTISPROCESSINGBAR/GETORDERBYTABLE";
export const GETORDERBYTABLE_SUCCESS = "FOODLISTISPROCESSINGBAR/GETORDERBYTABLE_SUCCESS";
export const GETORDERBYTABLE_FAIL = "FOODLISTISPROCESSINGBAR/GETORDERBYTABLE_FAIL";

export const GETDISHBYORDER = "FOODLISTISPROCESSINGBAR/GETDISHBYORDER";
export const GETDISHBYORDER_SUCCESS = "FOODLISTISPROCESSINGBAR/GETDISHBYORDER_SUCCESS";
export const GETDISHBYORDER_FAIL = "FOODLISTISPROCESSINGBAR/GETDISHBYORDER_FAIL";

export const UPDATEDORDERITEMISCOMPLETED = "FOODLISTISPROCESSINGBAR/UPDATEDORDERITEMISCOMPLETED";
export const UPDATEDORDERITEMISCOMPLETED_SUCCESS = "FOODLISTISPROCESSINGBAR/UPDATEDORDERITEMISCOMPLETED_SUCCESS";
export const UPDATEDORDERITEMISCOMPLETED_FAIL = "FOODLISTISPROCESSINGBAR/UPDATEDORDERITEMISCOMPLETED_FAIL";

export const UPDATEORDERITEMISOFF = "FOODLISTISPROCESSINGBAR/UPDATEORDERITEMISOFF";
export const UPDATEORDERITEMISOFF_SUCCESS = "FOODLISTISPROCESSINGBAR/UPDATEORDERITEMISOFF_SUCCESS";
export const UPDATEORDERITEMISOFF_FAIL = "FOODLISTISPROCESSINGBAR/UPDATEORDERITEMISOFF_FAIL";

export const ADDNOFITICATION = "FOODLISTISPROCESSINGBAR/ADDNOFITICATION";
export const ADDNOFITICATION_SUCCESS = "FOODLISTISPROCESSINGBAR/ADDNOFITICATION_SUCCESS";
export const ADDNOFITICATION_FAIL = "FOODLISTISPROCESSINGBAR/ADDNOFITICATION_FAIL";

export const SETDISHPAGE = "FOODLISTISPROCESSINGBAR/SETDISHPAGE";
export const SETORDERPAGE = "FOODLISTISPROCESSINGBAR/SETORDERPAGE";

export const SEARCHORDER = "FOODLISTISPROCESSINGBAR/SEARCHORDER";
export const SEARCHORDER_SUCCESS = "FOODLISTISPROCESSINGBAR/SEARCHORDER_SUCCESS";
export const SEARCHORDER_FAIL = "FOODLISTISPROCESSINGBAR/SEARCHORDER_FAIL";

export const STARTLOADING = "FOODLISTISPROCESSINGBAR/STARTLOADING";
export const STOPLOADING = "FOODLISTISPROCESSINGBAR/STOPLOADING";

export const GETUSERINFO = "FOODLISTISPROCESSINGBAR/GETUSERINFO";

export const UPDATEKITCHENBAR = "FOODLISTISPROCESSING/UPDATEKITCHENBAR"
export const SHOWMESSAGEBYNOTI = "FOODLISTISPROCESSINGBAR/SHOWMESSAGEBYNOTI"
export const UPDATEORDERBYNOTI = "FOODLISTISPROCESSINGBAR/UPDATEORDERBYNOTI";
export const GETPARAMSTABFOOD = "FOODLISTISPROCESSINGBAR/GETPARAMSTABFOOD";

export const GETACCOUNTINFOSTAFF = "FOODLISTISPROCESSINGBAR/GETACCOUNTINFOSTAFF";
export const GETACCOUNTINFOSTAFF_SUCCESS = "FOODLISTISPROCESSINGBAR/GETACCOUNTINFOSTAFF_SUCCESS";
export const GETACCOUNTINFOSTAFF_FAIL = "FOODLISTISPROCESSINGBAR/GETACCOUNTINFOSTAFF_FAIL";