export const CHECKED = 1;
export const NOT_CHECKED = 0;
export const IS_CONFIRM_CHECKIN = 0;
export const IS_ON_LOCATE = 1;
export const IS_PRINT_COMPLETE_COOKING = 2;
export const IS_AUDIO = 3;
export const IS_CALL_EMPLOYEE = 4;
export const IS_CHECK_IN_OUT = 5;

export const DEFAUL_CURRENCY_UNIT = 1;

export const GETPARTNERSETTING = "SETTINGGENERAL/GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS =
  "SETTINGGENERAL/GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "SETTINGGENERAL/GETPARTNERSETTING_FAIL";

export const UPDATEPARTNERSETTING = "SETTINGGENERAL/UPDATEPARTNERSETTING";
export const UPDATEPARTNERSETTING_SUCCESS =
  "SETTINGGENERAL/UPDATEPARTNERSETTING_SUCCESS";
export const UPDATEPARTNERSETTING_FAIL =
  "SETTINGGENERAL/UPDATEPARTNERSETTING_FAIL";

export const GETPARTNERBYID = "SETTINGGENERAL/GETPARTNERBYID";
export const GETPARTNERBYID_SUCCESS = "SETTINGGENERAL/GETPARTNERBYID_SUCCESS";
export const GETPARTNERBYID_FAIL = "SETTINGGENERAL/GETPARTNERBYID_FAIL";

export const GETCURRENCYUNIT = "SETTINGGENERAL/GETCURRENCYUNIT";
export const GETCURRENCYUNIT_SUCCESS =
  "SETTINGGENERAL/GETCURRENCYUNIT_SUCCESS";
export const GETCURRENCYUNIT_FAIL = "SETTINGGENERAL/GETCURRENCYUNIT_FAIL";
