

export const GETUNITITEMLIST = "SETTINGFOOD/GETUNITITEMLIST";
export const GETUNITITEMLIST_SUCCESS = "SETTINGFOOD/GETUNITITEMLIST_SUCCESS";
export const GETUNITITEMLIST_FAIL = "SETTINGFOOD/GETUNITITEMLIST_FAIL";

export const CREATEUNITITEM = "SETTINGFOOD/CREATEUNITITEM";
export const CREATEUNITITEM_SUCCESS = "SETTINGFOOD/CREATEUNITITEM_SUCCESS";
export const CREATEUNITITEM_FAIL = "SETTINGFOOD/CREATEUNITITEM_FAIL";

export const EDITUNITITEM = "SETTINGFOOD/EDITUNITITEM";
export const EDITUNITITEM_SUCCESS = "SETTINGFOOD/EDITUNITITEM_SUCCESS";
export const EDITUNITITEM_FAIL = "SETTINGFOOD/EDITUNITITEM_FAIL";

export const DELETEUNITITEM = "SETTINGFOOD/DELETEUNITITEM";
export const DELETEUNITITEM_SUCCESS = "SETTINGFOOD/DELETEUNITITEM_SUCCESS";
export const DELETEUNITITEM_FAIL = "SETTINGFOOD/DELETEUNITITEM_FAIL";


