export const CHECKED = 1;
export const NO_CHECKED = 0;

export const PAGE = 1;
export const LIMIT = 20;
export const USE = 3;
export const NOT_USE = 6;
export const MAX_ICON = "_20.svg";

export const GETAREALIST = "TABLEMANAGEMENT/GETAREALIST";
export const GETAREALIST_SUCCESS = "TABLEMANAGEMENT/GETAREALIST_SUCCESS";
export const GETAREALIST_FAIL = "TABLEMANAGEMENT/GETAREALIST_FAIL";

export const GETTABLETYPELIST = "TABLEMANAGEMENT/GETTABLETYPELIST";
export const GETTABLETYPELIST_SUCCESS = "TABLEMANAGEMENT/GETTABLETYPELIST_SUCCESS";
export const GETTABLETYPELIST_FAIL = "TABLEMANAGEMENT/GETTABLETYPELIST_FAIL";

export const GETTABLELIST = "TABLEMANAGEMENT/GETTABLELIST";
export const GETTABLELIST_SUCCESS = "TABLEMANAGEMENT/GETTABLELIST_SUCCESS";
export const GETTABLELIST_FAIL = "TABLEMANAGEMENT/GETTABLELIST_FAIL";

export const CREATETABLE = "TABLEMANAGEMENT/CREATETABLE";
export const CREATETABLE_SUCCESS = "TABLEMANAGEMENT/CREATETABLE_SUCCESS";
export const CREATETABLE_FAIL = "TABLEMANAGEMENT/CREATETABLE_FAIL";

export const DELETETABLE = "TABLEMANAGEMENT/DELETETABLE";
export const DELETETABLE_SUCCESS = "TABLEMANAGEMENT/DELETETABLE_SUCCESS";
export const DELETETABLE_FAIL = "TABLEMANAGEMENT/DELETETABLE_FAIL";

export const EDITTABLE = "TABLEMANAGEMENT/EDITTABLE";
export const EDITTABLE_SUCCESS = "TABLEMANAGEMENT/EDITTABLE_SUCCESS";
export const EDITTABLE_FAIL = "TABLEMANAGEMENT/EDITTABLE_FAIL";

export const SEARCHTABLE = "TABLEMANAGEMENT/SEARCHTABLE";
export const SEARCHTABLE_SUCCESS = "TABLEMANAGEMENT/SEARCHTABLE_SUCCESS";
export const SEARCHTABLE_FAIL = "TABLEMANAGEMENT/SEARCHTABLE_FAIL";

export const GETTABLEICON = "TABLEMANAGEMENT/GETTABLEICON";
export const GETTABLEICON_SUCCESS = "TABLEMANAGEMENT/GETTABLEICON_SUCCESS";
export const GETTABLEICON_FAIL = "TABLEMANAGEMENT/GETTABLEICON_FAIL";

export const LOADTABLESHAPE = "TABLEMANAGEMENT/LOADTABLESHAPE";
export const UNLOADTABLESHAPE = "TABLEMANAGEMENT/UNLOADTABLESHAPE";

export const SETPAGE = "TABLEMANAGEMENT/SETPAGE";

export const SETSEARCHING = "TABLEMANAGEMENT/SETSEARCHING";
export const SETNOSEARCHING = "TABLEMANAGEMENT/SETNOSEARCHING";

export const RESETTABLE = "TABLEMANAGEMENT/RESETTABLE"
export const TABLE_TYPES = {
  vip: 2,
  normal: 1
};

export const GETTABLELISTALL = "TABLEMANAGEMENT/GETTABLELISTALL";
export const GETTABLELISTALL_SUCCESS = "TABLEMANAGEMENT/GETTABLELISTALL_SUCCESS";
export const GETTABLELISTALL_FAIL = "TABLEMANAGEMENT/GETTABLELISTALL_FAIL";

export const GETINFOPARTNER = "TABLEMANAGEMENT/GETINFOPARTNER";
export const GETINFOPARTNER_SUCCESS = "TABLEMANAGEMENT/GETINFOPARTNER_SUCCESS";
export const GETINFOPARTNER_FAIL = "TABLEMANAGEMENT/GETINFOPARTNER_FAIL";

export const GETPARTNERSETTING = "TABLEMANAGEMENT/GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS = "TABLEMANAGEMENT/GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "TABLEMANAGEMENT/GETPARTNERSETTING_FAIL";

export const NOTI_ACTION_STAFF_ORDER_ITEM = "staff_order_item";
export const NOTI_ACTION_RESET_TABLE = "reset_table";

// Các action của noti để update table management
export const ACTION_UPDATE_TABLE_MANAGEMENT = [
  "staff_order_item",
  "reset_table",
]

export const UPDATETABLEBYNOTI = "TABLEMANAGEMENT/UPDATETABLEBYNOTI"