export const PAGE = 1;
export const LIMIT = 20;

export const GETITEMLIST = "FOODMANAGEMENT/GETITEMLIST";
export const GETITEMLIST_SUCCESS = "FOODMANAGEMENT/GETITEMLIST_SUCCESS";
export const GETITEMLIST_FAIL = "FOODMANAGEMENT/GETITEMLIST_FAIL";

export const GETITEMLISTBYSEARCHADVANCED = "FOODMANAGEMENT/GETITEMLISTBYSEARCHADVANCED";
export const GETITEMLISTBYSEARCHADVANCED_SUCCESS = "FOODMANAGEMENT/GETITEMLISTBYSEARCHADVANCED_SUCCESS";
export const GETITEMLISTBYSEARCHADVANCED_FAIL = "FOODMANAGEMENT/GETITEMLISTBYSEARCHADVANCED_FAIL";

export const DELETEITEM = "FOODMANAGEMENT/DELETEITEM";
export const DELETEITEM_SUCCESS = "FOODMANAGEMENT/DELETEITEM_SUCCESS";
export const DELETEITEM_FAIL = "FOODMANAGEMENT/DELETEITEM_FAIL";

export const CREATEITEM = "FOODMANAGEMENT/CREATEITEM";
export const CREATEITEM_SUCCESS = "FOODMANAGEMENT/CREATEITEM_SUCCESS";
export const CREATEITEM_FAIL = "FOODMANAGEMENT/CREATEITEM_FAIL";

export const EDITITEM = "FOODMANAGEMENT/EDITITEM";
export const EDITITEM_SUCCESS = "FOODMANAGEMENT/EDITITEM_SUCCESS";
export const EDITITEM_FAIL = "FOODMANAGEMENT/EDITITEM_FAIL";

export const GETUNITITEMLIST = "FOODMANAGEMENT/GETUNITITEMLIST";
export const GETUNITITEMLIST_SUCCESS = "FOODMANAGEMENT/GETUNITITEMLIST_SUCCESS";
export const GETUNITITEMLIST_FAIL = "FOODMANAGEMENT/GETUNITITEMLIST_FAIL";

export const GETCATEGORYITEMLIST = "FOODMANAGEMENT/GETCATEGORYITEMLIST";
export const GETCATEGORYITEMLIST_SUCCESS = "FOODMANAGEMENT/GETCATEGORYITEMLIST_SUCCESS";
export const GETCATEGORYITEMLIST_FAIL = "FOODMANAGEMENT/GETCATEGORYITEMLIST_FAIL";

export const GETGENERATEBYID = "FOODMANAGEMENT/GETGENERATEBYID";
export const GETGENERATEBYID_SUCCESS = "FOODMANAGEMENT/GETGENERATEBYID_SUCCESS";
export const GETGENERATEBYID_FAIL = "FOODMANAGEMENT/GETGENERATEBYID_FAIL";

export const UPLOADIMAGEITEM = "FOODMANAGEMENT/UPLOADIMAGEITEM";
export const UPLOADIMAGEITEM_SUCCESS = "FOODMANAGEMENT/UPLOADIMAGEITEM_SUCCESS";
export const UPLOADIMAGEITEM_FAIL = "FOODMANAGEMENT/UPLOADIMAGEITEM_FAIL";

export const START_LOADING = "FOODMANAGEMENT/START_LOADING";

export const GETINFOVATSETTING = "FOODMANAGEMENT/GETINFOVATSETTING";
export const GETINFOVATSETTING_SUCCESS = "FOODMANAGEMENT/GETINFOVATSETTING_SUCCESS";
export const GETINFOVATSETTING_FAIL = "FOODMANAGEMENT/GETINFOVATSETTING_FAIL";

export const LIMIT_ADDON = 12;

export const GETADDONLIST = "FOODMANAGEMENT/GETADDONLIST";
export const GETADDONLIST_SUCCESS = "FOODMANAGEMENT/GETADDONLIST_SUCCESS";
export const GETADDONLIST_FAIL = "FOODMANAGEMENT/GETADDONLIST_FAIL";