export const CREATEAREA = "SETTINGTABLE/CREATEAREA";
export const CREATEAREA_SUCCESS = "SETTINGTABLE/CREATEAREA_SUCCESS";
export const CREATEAREA_FAIL = "SETTINGTABLE/CREATEAREA_FAIL";

export const EDITAREA = "SETTINGTABLE/EDITAREA";
export const EDITAREA_SUCCESS = "SETTINGTABLE/EDITAREA_SUCCESS";
export const EDITAREA_FAIL = "SETTINGTABLE/EDITAREA_FAIL";

export const DELETEAREA = "SETTINGTABLE/DELETEAREA";
export const DELETEAREA_SUCCESS = "SETTINGTABLE/DELETEAREA_SUCCESS";
export const DELETEAREA_FAIL = "SETTINGTABLE/DELETEAREA_FAIL";

export const GETAREALIST = "SETTINGTABLE/GETAREALIST";
export const GETAREALIST_SUCCESS = "SETTINGTABLE/GETAREALIST_SUCCESS";
export const GETAREALIST_FAIL = "SETTINGTABLE?GETAREALIST_FAIL";


