export const GETLISTREQUESTPAYMENT = "REQUESTPAYMENT/GETLISTREQUESTPAYMENT";
export const GETLISTREQUESTPAYMENT_SUCCESS = "REQUESTPAYMENT/GETLISTREQUESTPAYMENT_SUCCESS";
export const GETLISTREQUESTPAYMENT_FAIL = "REQUESTPAYMENT/GETLISTREQUESTPAYMENT_FAIL";

export const GETDETAILREQUESTPAYMENT = "REQUESTPAYMENT/GETDETAILREQUESTPAYMENT";
export const GETDETAILREQUESTPAYMENT_SUCCESS = "REQUESTPAYMENT/GETDETAILREQUESTPAYMENT_SUCCESS";
export const GETDETAILREQUESTPAYMENT_FAIL = "REQUESTPAYMENT/GETDETAILREQUESTPAYMENT_FAIL";

export const SENDPROVISIVOTE = "REQUESTPAYMENT/SENDPROVISIVOTE";
export const SENDPROVISIVOTE_SUCCESS = "REQUESTPAYMENT/SENDPROVISIVOTE_SUCCESS";
export const SENDPROVISIVOTE_FAIL = "REQUESTPAYMENT/SENDPROVISIVOTE_FAIL";

export const GETORDERITEMBYID = "REQUESTPAYMENT/GETORDERITEMBYID";
export const GETORDERITEMBYID_SUCCESS = "REQUESTPAYMENT/GETORDERITEMBYID_SUCCESS";
export const GETORDERITEMBYID_FAIL = "REQUESTPAYMENT/GETORDERITEMBYID_FAIL";

export const GETINFODETAILPROVISIVOTE = "REQUESTPAYMENT/GETINFODETAILPROVISIVOTE";
export const GETINFODETAILPROVISIVOTE_SUCCESS = "REQUESTPAYMENT/GETINFODETAILPROVISIVOTE_SUCCESS";
export const GETINFODETAILPROVISIVOTE_FAIL = "REQUESTPAYMENT/GETINFODETAILPROVISIVOTE_FAIL";

export const UPDATESTATUSFOODORDERD = "REQUESTPAYMENT/UPDATESTATUSFOODORDERD";

export const UPDATEAMOUNTITEMORDERED = "REQUESTPAYMENT/UPDATEAMOUNTITEMORDERED";
export const UPDATEAMOUNTITEMORDERED_SUCCESS = "REQUESTPAYMENT/UPDATEAMOUNTITEMORDERED_SUCCESS";
export const UPDATEAMOUNTITEMORDERED_FAIL = "REQUESTPAYMENT/UPDATEAMOUNTITEMORDERED_FAIL";

export const CANCELFOODORDERED = "REQUESTPAYMENT/CANCELFOODORDERED";
export const CANCELFOODORDERED_SUCCESS = "REQUESTPAYMENT/CANCELFOODORDERED_SUCCESS";
export const CANCELFOODORDERED_FAIL = "REQUESTPAYMENT/CANCELFOODORDERED_FAIL";


export const LIMITREQPAYMENT = 10;
export const PAGEINIT = 1;

export const STATUS = {
  WAITING_HANDLE : 1,
  SEND_BILL : 2,
  COMPLETED_HANDLED : 3,
  CANCEL_REQPAYMENT :4,
  REPORT_WRONG : 5,
  REPORT_BILL_WRONG : 6
}