export const CREATE_AREA = "CREATE_AREA";
export const CREATE_AREA_SUCCESS = "CREATE_AREA_SUCCESS";
export const CREATE_AREA_FAILURE = "CREATE_AREA_FAILURE";

export const EDIT_AREA = "EDIT_AREA";
export const EDIT_AREA_SUCCESS = "EDIT_AREA_SUCCESS";
export const EDIT_AREA_FAILURE = "EDIT_AREA_FAILURE";

export const GET_LIST_AREA = "GET_LIST_AREA";
export const GET_LIST_AREA_SUCCESS = "GET_LIST_AREA_SUCCESS";
export const GET_LIST_AREA_FAILURE = "GET_LIST_AREA_FAILURE";

export const GET_LIST_AREA_BY_PARTNER = "GET_LIST_AREA_BY_PARTNER";
export const GET_LIST_AREA_BY_PARTNER_SUCCESS = "GET_LIST_AREA_BY_PARTNER_SUCCESS";
export const GET_LIST_AREA_BY_PARTNER_FAILURE = "GET_LIST_AREA_BY_PARTNER_FAILURE";

export const GET_AREA_INFO = "GET_AREA_INFO";
export const GET_AREA_INFO_SUCCESS = "GET_AREA_INFO_SUCCESS";
export const GET_AREA_INFO_FAILURE = "GET_AREA_INFO_FAILURE";

export const DELETE_AREA = "DELETE_AREA";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCESS";
export const DELETE_AREA_FAILURE = "DELETE_AREA_FAILURE";

export const SEARCH_AREA = "SEARCH_AREA";
export const SEARCH_AREA_SUCCESS = "SEARCH_AREA_SUCCESS";
export const SEARCH_AREA_FAILURE = "SEARCH_AREA_FAILURE";

export const SELECT_AREA = "SELECT_AREA";
export const DESELECT_AREA = "DESELECT_AREA";

export const GET_AREA_SUB_ICON = "GET_AREA_SUB_ICON";
export const GET_AREA_SUB_ICON_SUCCESS = "GET_AREA_SUB_ICON_SUCCESS";
export const GET_AREA_SUB_ICON_FAILURE = "GET_AREA_SUB_ICON_FAILURE";
