
export const GET_INFO_PARTNER = "DETAILRESTAURANT/GETINFOPARTNER";
export const GET_INFO_PARTNER_SUCCESS = "DETAILRESTAURANT/GETINFOPARTNER_SUCCESS";
export const GET_INFO_PARTNER_FAIL = "DETAILRESTAURANT/GETINFOPARTNER_FAIL";

export const GETCATEGORYITEMLIST = "DETAILRESTAURANT/GETCATEGORYITEMLIST";
export const GETCATEGORYITEMLIST_SUCCESS = "DETAILRESTAURANT/GETCATEGORYITEMLIST_SUCCESS";
export const GETCATEGORYITEMLIST_FAIL = "DETAILRESTAURANT/GETCATEGORYITEMLIST_FAIL";

export const GETCOMBOITEMLIST = "DETAILRESTAURANT/GETCOMBOITEMLIST";
export const GETCOMBOITEMLIST_SUCCESS = "DETAILRESTAURANT/GETCOMBOITEMLIST_SUCCESS";
export const GETCOMBOITEMLIST_FAIL = "DETAILRESTAURANT/GETCOMBOITEMLIST_FAIL";

export const GETCOMBOBYID = "DETAILRESTAURANT/GETCOMBOBYID";
export const GETCOMBOBYID_SUCCESS = "DETAILRESTAURANT/GETCOMBOBYID_SUCCESS";
export const GETCOMBOBYID_FAIL = "DETAILRESTAURANT/GETCOMBOBYID_FAIL";

export const GETPARTNERSETTING = "DETAILRESTAURANT/GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS = "DETAILRESTAURANT/GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "DETAILRESTAURANT/GETPARTNERSETTING_FAIL";

export const GETORDERITEM = "DETAILRESTAURANT/GETORDERITEM";
export const GETORDERITEM_SUCCESS = "DETAILRESTAURANT/GETORDERITEM_SUCCESS";
export const GETORDERITEM_FAIL = "DETAILRESTAURANT/GETORDERITEM_FAIL";

export const GETTABLEBYID = "DETAILRESTAURANT/GETTABLEBYID";
export const GETTABLEBYID_SUCCESS = "DETAILRESTAURANT/GETTABLEBYID_SUCCESS";
export const GETTABLEBYID_FAIL = "DETAILRESTAURANT/GETTABLEBYID_FAIL";

export const CALLSTAFFINSERTNOTI = "DETAILRESTAURANT/CALLSTAFFINSERTNOTI";