export const GETBOOKINGTABLE = "BOOKINGTABLE/GETBOOKINGTABLE";
export const GETBOOKINGTABLE_SUCCESS = "BOOKINGTABLE/GETBOOKINGTABLE_SUCCESS";
export const GETBOOKINGTABLE_FAIL = "BOOKINGTABLE/GETBOOKINGTABLE_FAIL";

export const GETBOOKINGBYID = "BOOKINGTABLE/GETBOOKINGBYID";
export const GETBOOKINGBYID_SUCCESS = "BOOKINGTABLE/GETBOOKINGBYID_SUCCESS";
export const GETBOOKINGBYID_FAIL = "BOOKINGTABLE/GETBOOKINGBYID_FAIL";

export const ADDBOOKINGTABLE = "BOOKINGTABLE/ADDBOOKINGTABLE";
export const ADDBOOKINGTABLE_SUCCESS = "BOOKINGTABLE/ADDBOOKINGTABLE_SUCCESS";
export const ADDBOOKINGTABLE_FAIL = "BOOKINGTABLE/ADDBOOKINGTABLE_FAIL";

export const EDITBOOKINGTABLE = "BOOKINGTABLE/EDITBOOKINGTABLE";
export const EDITBOOKINGTABLE_SUCCESS = "BOOKINGTABLE/EDITBOOKINGTABLE_SUCCESS";
export const EDITBOOKINGTABLE_FAIL = "BOOKINGTABLE/EDITBOOKINGTABLE_FAIL";

export const GETLISTTABLESTATUS = "BOOKINGTABLE/GETLISTTABLESTATUS";
export const GETLISTTABLESTATUS_SUCCESS = "BOOKINGTABLE/GETLISTTABLESTATUS_SUCCESS";
export const GETLISTTABLESTATUS_FAIL = "BOOKINGTABLE/GETLISTTABLESTATUS_FAIL";

export const GETLISTAREA = "BOOKINGTABLE/GETLISTAREA";
export const GETLISTAREA_SUCCESS = "BOOKINGTABLE/GETLISTAREA_SUCCESS";
export const GETLISTAREA_FAIL = "BOOKINGTABLE/GETLISTAREA_FAIL";

export const SORTTABLEBOOKING = "BOOKINGTABLE/SORTTABLEBOOKING";
export const SORTTABLEBOOKING_SUCCESS = "BOOKINGTABLE/SORTTABLEBOOKING_SUCCESS";
export const SORTTABLEBOOKING_FAIL = "BOOKINGTABLE/SORTTABLEBOOKING_FAIL";

export const GETLISTTABLEBOOKING = "BOOKINGTABLE/GETLISTTABLEBOOKING";
export const GETLISTTABLEBOOKING_SUCCESS = "BOOKINGTABLE/GETLISTTABLEBOOKING_SUCCESS";
export const GETLISTTABLEBOOKING_FAIL = "BOOKINGTABLE/GETLISTTABLEBOOKING_FAIL";

export const UPDATE_STATUS_BOOKING = "BOOKINGTABLE/UPDATE_STATUS_BOOKING";
export const UPDATE_STATUS_BOOKING_SUCCESS = "BOOKINGTABLE/UPDATE_STATUS_BOOKING_SUCCESS";
export const UPDATE_STATUS_BOOKING_FAIL = "BOOKINGTABLE/UPDATE_STATUS_BOOKING_FAIL";

export const RESETBOOKINGDETAIL = "BOOKINGTABLE/RESETBOOKINGDETAIL";

export const GETLISTAREABYPARNERID = "BOOKINGTABLE/GETLISTAREABYPARNERID";
export const GETLISTAREABYPARNERID_SUCCESS = "BOOKINGTABLE/GETLISTAREABYPARNERID_SUCCESS";
export const GETLISTAREABYPARNERID_FAIL = "BOOKINGTABLE/GETLISTAREABYPARNERID_FAIL";

export const UPDATEBOOKINGTABLEBYNOTI = "BOOKINGTABLE/UPDATEBOOKINGTABLEBYNOTI";
export const UPDATELISTBOOKING = "BOOKINGTABLE/UPDATELISTBOOKING";