export const GETLISTSHIFT = "SHIFTMANAGAMENT/GETLISTSHIFT";
export const GETLISTSHIFT_SUCCESS = "SHIFTMANAGAMENT/GETLISTSHIFT_SUCCESS";
export const GETLISTSHIFT_FAIL = "SHIFTMANAGAMENT/GETLISTSHIFT_FAIL";

export const ADDSHIFT ="SHIFTMANAGAMENT/ADDSHIFT";
export const ADDSHIFT_SUCCESS ="SHIFTMANAGAMENT/ADDSHIFT_SUCCESS";
export const ADDSHIFT_FAIL ="SHIFTMANAGAMENT/ADDSHIFT_FAIL";

export const EDITSHIFT ="SHIFTMANAGAMENT/EDITSHIFT";
export const EDITSHIFT_SUCCESS ="SHIFTMANAGAMENT/EDITSHIFT_SUCCESS";
export const EDITSHIFT_FAIL ="SHIFTMANAGAMENT/EDITSHIFT_FAIL";

export const DELETESHIFT ="SHIFTMANAGAMENT/DELETESHIFT";