export const GET_LIST_TABLE = "GET_LIST_TABLE";
export const GET_LIST_TABLE_SUCCESS = "GET_LIST_TABLE_SUCCESS";
export const GET_LIST_TABLE_FAILURE = "GET_LIST_TABLE_FAILURE";

export const ADD_COMBINE_TABLE = "ADD_COMBINE_TABLE";
export const REMOVE_COMBINE_TABLE = "REMOVE_COMBINE_TABLE";

export const COMBINE_TABLE = "COMBINE_TABLE";
export const COMBINE_TABLE_SUCCESS = "COMBINE_TABLE_SUCCESS";
export const COMBINE_TABLE_FAILURE = "COMBINE_TABLE_FAILURE";

export const SELECT_QRCODE_TABLE = "SELECT_QRCODE_TABLE";
export const DESELECT_QRCODE_TABLE = "DESELECT_QRCODE_TABLE";

export const SELECT_IN_USE_TABLE = "SELECT_IN_USE_TABLE";
export const DESELECT_IN_USE_TABLE = "DESELECT_IN_USE_TABLE";

export const SELECT_IN_USE_TABLE_FEATURE = "SELECT_IN_USE_TABLE_FEATURE";
export const DESELECT_IN_USE_TABLE_FEATURE = "DESELECT_IN_USE_TABLE_FEATURE";

export const GET_TABLE_ORDER = "GET_TABLE_ORDER";
export const GET_TABLE_ORDER_SUCCESS = "GET_TABLE_ORDER_SUCCESS";
export const GET_TABLE_ORDER_FAILURE = "GET_TABLE_ORDER_FAILURE";

export const SELECT_ORDER = "SELECT_ORDER";
export const DESELECT_ORDER = "DESELECT_ORDER";

export const GET_COMBINED_TABLE = "GET_COMBINED_TABLE";
export const GET_COMBINED_TABLE_SUCCESS = "GET_COMBINED_TABLE_SUCCESS";
export const GET_COMBINED_TABLE_FAILURE = "GET_COMBINED_TABLE_FAILURE";

export const CHANGE_TABLE_STATUS = "CHANGE_TABLE_STATUS";

export const GETITEM_COMBOLIST = "GETITEM_COMBOLIST";
export const GETITEM_COMBOLIST_SUCCESS = "GETITEM_COMBOLIST_SUCCESS";
export const GETITEM_COMBOLIST_FAIL = "GETITEM_COMBOLIST_FAIL";

export const RESETITEMCOMBOLIST = "RESETITEMCOMBOLIST";

export const LIMIT_COMBO_ITEM = 6;

export const GETCOMBO = "GETCOMBO";
export const GETCOMBO_SUCCESS = "GETCOMBO_SUCCESS";
export const GETCOMBO_FAIL = "GETCOMBO_FAIL";

export const GETPARTNERSETTING = "GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS = "GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "GETPARTNERSETTING_FAIL";

export const GETCOMBOITEMLIST = "GETCOMBOITEMLIST";
export const GETCOMBOITEMLIST_SUCCESS = "GETCOMBOITEMLIST_SUCCESS";
export const GETCOMBOITEMLIST_FAIL = "GETCOMBOITEMLIST_FAIL";

export const GETORDERITEM = "GETORDERITEM";
export const GETORDERITEM_SUCCESS = "GETORDERITEM_SUCCESS";
export const GETORDERITEM_FAIL = "GETORDERITEM_FAIL";

export const GETCATEGORYITEMLIST = "GETCATEGORYITEMLIST";
export const GETCATEGORYITEMLIST_SUCCESS = "GETCATEGORYITEMLIST_SUCCESS";
export const GETCATEGORYITEMLIST_FAIL = "GETCATEGORYITEMLIST_FAIL";

export const GETCOMBOBYID = "GETCOMBOBYID";
export const GETCOMBOBYID_SUCCESS = "GETCOMBOBYID_SUCCESS";
export const GETCOMBOBYID_FAIL = "GETCOMBOBYID_FAIL";

export const CREATEORDER = "CREATEORDER";
export const CREATEORDER_SUCCESS = "CREATEORDER_SUCCESS";
export const CREATEORDER_FAIL = "CREATEORDER_FAIL";
export const GETNOTIFICATIONSLIST = "GETNOTIFICATIONSLIST";
export const GETNOTIFICATIONSLIST_SUCCESS = "GETNOTIFICATIONSLIST_SUCCESS";
export const GETNOTIFICATIONSLIST_FAILURE = "GETNOTIFICATIONSLIST_FAILURE";

export const POSTORDERITEMBYID = "POSTORDERITEMBYID";
export const POSTORDERITEMBYID_SUCCESS = "POSTORDERITEMBYID_SUCCESS";
export const POSTORDERITEMBYID_FAIL = "POSTORDERITEMBYID_FAIL";

export const GETORDERITEMBYID = "GETORDERITEMBYID";
export const GETORDERITEMBYID_SUCCESS = "GETORDERITEMBYID_SUCCESS";
export const GETORDERITEMBYID_FAIL = "GETORDERITEMBYID_FAIL";

export const POSTORDERITEMCOMBOBYID = "POSTORDERITEMCOMBOBYID";
export const POSTORDERITEMCOMBOBYID_SUCCESS = "POSTORDERITEMCOMBOBYID_SUCCESS";
export const POSTORDERITEMCOMBOBYID_FAIL = "POSTORDERITEMCOMBOBYID_FAIL";
export const UPDATESTATUSTABLE = "UPDATESTATUSTABLE";
export const UPDATESTATUSTABLE_SUCCESS = "UPDATESTATUSTABLE_SUCCESS";
export const UPDATESTATUSTABLE_FAILURE = "UPDATESTATUSTABLE_FAILURE";

export const GETCOMBOITEMLISTONLY = "GETCOMBOITEMLISTONLY";
export const GETCOMBOITEMLISTONLY_SUCCESS = "GETCOMBOITEMLISTONLY_SUCCESS";
export const GETCOMBOITEMLISTONLY_FAIL = "GETCOMBOITEMLISTONLY_FAIL";

export const SETORDERID = "TABLELIST/SETORDERID";

export const UPDATEICONTABLEBYNOTI = "TABLELIST/UPDATEICONTABLEBYNOTI"

// Get notifications
export const GETNOTIFICATIONS = "TABLELIST/GETNOTIFICATIONS";
export const GETNOTIFICATIONS_SUCCESS = "TABLELIST/GETNOTIFICATIONS_SUCCESS";
export const GETNOTIFICATIONS_FAILURE = "TABLELIST/GETNOTIFICATIONS_FAILURE";

export const GETNOTIFICATIONSFORTABLE = "TABLELIST/GETNOTIFICATIONSFORTABLE";

export const CHANGEACTIONSTATUS = "TABLELIST/CHANGEACTIONSTATUS";
export const CHANGEACTIONSTATUS_SUCCESS = "TABLELIST/CHANGEACTIONSTATUS_SUCCESS";
export const CHANGEACTIONSTATUS_FAIL = "TABLELIST/CHANGEACTIONSTATUS_FAIL";

export const CREATEORDERBYNOTI = "TABLELIST/CREATEORDERBYNOTI";
export const CREATEORDERBYNOTI_SUCCESS = "TABLELIST/CREATEORDERBYNOTI_SUCCESS";
export const CREATEORDERBYNOTI_FAIL = "TABLELIST/CREATEORDERBYNOTI_FAIL";

export const UPDATESTATUSNOTI = "TABLELIST/UPDATESTATUSNOTI";
export const UPDATESTATUSNOTI_SUCCESS = "TABLELIST/UPDATESTATUSNOTI_SUCCESS";
export const UPDATESTATUSNOTI_FAIL = "TABLELIST/UPDATESTATUSNOTI_FAIL";

export const REMOVENOTICEFORTABLE = "TABLELIST/REMOVENOTICEFORTABLE";
