export const GETAREAINFO = "TABLEARRANGEMENT/GETAREAINFO";
export const GETAREAINFO_SUCCESS = "TABLEARRANGEMENT/GETAREAINFO_SUCCESS";
export const GETAREAINFO_FAIL = "TABLEARRANGEMENT/GETAREAINFO_FAIL";

export const EDITAREA = "EDITAREA";
export const EDITAREA_SUCCESS = "EDITAREA_SUCCESS";
export const EDITAREA_FAIL = "EDITAREA_FAIL";

export const GETTABLELIST = "TABLEARRANGEMENT/GETTABLELIST";
export const GETTABLELIST_SUCCESS = "TABLEARRANGEMENT/GETTABLELIST_SUCCESS";
export const GETTABLELIST_FAIL = "TABLEARRANGEMENT/GETTABLELIST_FAIL";

export const GETTABLELISTBYAREAID = "TABLEARRANGEMENT/GETTABLELISTBYAREAID";
export const GETTABLELISTBYAREAID_SUCCESS = "TABLEARRANGEMENT/GETTABLELISTBYAREAID_SUCCESS";
export const GETTABLELISTBYAREAID_FAIL = "TABLEARRANGEMENT/GETTABLELISTBYAREAID_FAIL";

export const GETTABLELISTARRANGEMENTBYID = "TABLEARRANGEMENT/GETTABLELISTARRANGEMENTBYID";
export const GETTABLELISTARRANGEMENTBYID_SUCCESS = "TABLEARRANGEMENT/GETTABLELISTARRANGEMENTBYID_SUCCESS";
export const GETTABLELISTARRANGEMENTBYID_FAIL = "TABLEARRANGEMENT/GETTABLELISTARRANGEMENTBYID_FAIL";

export const POSTTABLELISTARRANGEMENTBYID = "TABLEARRANGEMENT/POSTTABLELISTARRANGEMENTBYID";
export const POSTTABLELISTARRANGEMENTBYID_SUCCESS = "TABLEARRANGEMENT/POSTTABLELISTARRANGEMENTBYID_SUCCESS";
export const POSTTABLELISTARRANGEMENTBYID_FAIL = "TABLEARRANGEMENT/POSTTABLELISTARRANGEMENTBYID_FAIL";

export const SEARCHTABLE = "TABLEARRANGEMENT/SEARCHTABLE";

export const GETAREAICON = "TABLEARRANGEMENT/GETAREAICON"
export const GETAREAICON_SUCCESS = "TABLEARRANGEMENT/GETAREAICON_SUCCESS"
export const GETAREAICON_FAIL = "TABLEARRANGEMENT/GETAREAICON_FAIL"
