export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_FAILURE = "GET_ORDER_DETAIL_FAILURE";

export const SELECT_PAYMENT_METHOD = "SELECT_PAYMENT_METHOD";
export const DESELECT_PAYMENT_METHOD = "DESELECT_PAYMENT_METHOD";

export const GET_INFO_PARTNER = "GET_INFO_PARTNER";
export const GET_INFO_PARTNER_SUCCESS = "GET_INFO_PARTNER_SUCCESS";
export const GET_INFO_PARTNER_FAIL = "GET_INFO_PARTNER_FAIL";