export const SHOW_POPUP_BY_DAY = 0;
export const SHOW_POPUP_BY_WEEK = 1;
export const SHOW_POPUP_BY_MONTH = 2;
export const SHOW_POPUP_BY_QUATERLY = 3;
export const SHOW_POPUP_BY_YEAR = 4;
export const LINE_NAME = "line";
export const COLLUMN_NAME=  "collumn";

export const GETPARTNERSETTING = "REPORTMANAGEMENT/GETPARTNERSETTING";
export const GETPARTNERSETTING_SUCCESS = "REPORTMANAGEMENT/GETPARTNERSETTING_SUCCESS";
export const GETPARTNERSETTING_FAIL = "REPORTMANAGEMENT/GETPARTNERSETTING_FAIL";

export const GETREPORTOVERVIEW = "REPORTMANAGEMENT/GETREPORTOVERVIEW";
export const GETREPORTOVERVIEW_SUCCESS = "REPORTMANAGEMENT/GETREPORTOVERVIEW_SUCCESS";
export const GETREPORTOVERVIEW_FAIL = "REPORTMANAGEMENT/GETREPORTOVERVIEW_FAIL";

export const GETGUESTTABLEBYDATE = "REPORTMANAGEMENT/GETGUESTTABLEBYDATE";
export const GETGUESTTABLEBYDATE_SUCCESS = "REPORTMANAGEMENT/GETGUESTTABLEBYDATE_SUCCESS";
export const GETGUESTTABLEBYDATE_FAIL = "REPORTMANAGEMENT/GETGUESTTABLEBYDATE_FAIL";

export const GETGUESTTABLEBYCURRENTDATE = "REPORTMANAGEMENT/GETGUESTTABLEBYCURRENTDATE";
export const GETGUESTTABLEBYCURRENTDATE_SUCCESS = "REPORTMANAGEMENT/GETGUESTTABLEBYCURRENTDATE_SUCCESS";
export const GETGUESTTABLEBYCURRENTDATE_FAIL = "REPORTMANAGEMENT/GETGUESTTABLEBYCURRENTDATE_FAIL";

export const GETREVENUEBYDATE = "REPORTMANAGEMENT/GETREVENUEBYDATE";
export const GETREVENUEBYDATE_SUCCESS = "REPORTMANAGEMENT/GETREVENUEBYDATE_SUCCESS";
export const GETREVENUEBYDATE_FAIL = "REPORTMANAGEMENT/GETREVENUEBYDATE_FAIL";

export const GETREVENUEBYMONTH = "REPORTMANAGEMENT/GETREVENUEBYMONTH";
export const GETREVENUEBYMONTH_SUCCESS = "REPORTMANAGEMENT/GETREVENUEBYMONTH_SUCCESS";
export const GETREVENUEBYMONTH_FAIL = "REPORTMANAGEMENT/GETREVENUEBYMONTH_FAIL";

export const GETREVENUEBYYEAR = "REPORTMANAGEMENT/GETREVENUEBYYEAR";
export const GETREVENUEBYYEAR_SUCCESS = "REPORTMANAGEMENT/GETREVENUEBYYEAR_SUCCESS";
export const GETREVENUEBYYEAR_FAIL = "REPORTMANAGEMENT/GETREVENUEBYYEAR_FAIL";

export const GETREVENUETOPFOODBYDATE = "REPORTMANAGEMENT/GETREVENUETOPFOODBYDATE";
export const GETREVENUETOPFOODBYDATE_SUCCESS = "REPORTMANAGEMENT/GETREVENUETOPFOODBYDATE_SUCCESS";
export const GETREVENUETOPFOODBYDATE_FAIL = "REPORTMANAGEMENT/GETREVENUETOPFOODBYDATE_FAIL";

export const GETREVENUETOPDRINKBYDATE = "REPORTMANAGEMENT/GETREVENUETOPDRINKBYDATE";
export const GETREVENUETOPDRINKBYDATE_SUCCESS = "REPORTMANAGEMENT/GETREVENUETOPDRINKBYDATE_SUCCESS";
export const GETREVENUETOPDRINKBYDATE_FAIL = "REPORTMANAGEMENT/GETREVENUETOPDRINKBYDATE_FAIL";

export const GETTOTALSTAFFWORKINGBYDATE = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYDATE";
export const GETTOTALSTAFFWORKINGBYDATE_SUCCESS = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYDATE_SUCCESS";
export const GETTOTALSTAFFWORKINGBYDATE_FAIL = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYDATE_FAIL";

export const GETTOTALSTAFFWORKINGBYWEEK = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYWEEK";
export const GETTOTALSTAFFWORKINGBYWEEK_SUCCESS = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYWEEK_SUCCESS";
export const GETTOTALSTAFFWORKINGBYWEEK_FAIL = "REPORTMANAGEMENT/GETTOTALSTAFFWORKINGBYWEEK_FAIL";